title: iris.ch
subtitle: La plus badass des russes portugaises du design valaisan
description: Site web d'Iris T.
author:
    name: Studio ANDco Sàrl
    twitter: ANDco_o
email: hello@andco.ch
lang: fr_CH
logo: tile.png

seo:
    type: Business

street: "Avenue du Ritz 35"
city: "Sion"
zip: "1950"
state: "Valais"
country: "Suisse"
latitude: "46.235885"
longitude: "7.3578723"

social:
  name: iris.ch
  links:

twitter:
    username: "Twitter"

facebook:
    app_id: Facebook APP id
    publisher: "https://www.facebook.com/andcohello"

google_site_verification: googleddcee30cf477c8ba
ga: Google Analytics ID

baseurl: "iris.ch"
url: "https://studioandco.github.io"

collections:
    projects:
        output: true
        permalink: /projects/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
    values:
      image: /files/facebook.png

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json

# Github forced settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false

kramdown:
    input: GFM
    hard_wrap: false

# Sitemap

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
